CREATE SCHEMA IF NOT EXISTS `Music_Quiz` DEFAULT CHARACTER SET utf8 ;
USE `Music_Quiz` ;

CREATE TABLE IF NOT EXISTS `Music_Quiz`.`User` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
